### ISSUE TITLE
支持后台无权限打开Activity吗

### ISSUE THREAD

**Issue by laibinzhi** [Pangu-Immortal/KeepAlivePerfect#19]
支持

**Comment by Pangu-Immortal** [comment]
支持，后台无权限弹出Activity，不需要任何权限。已经适配了所有的机型，包括国内的全部机型都支持，已经全面测试通过。包括Android14，可以加群或者邮件联系我。国内和海外所有机型全支持，非常完美。代码合规，可以上架Google和国内市场。。

**Comment by Pangu-Immortal** [comment]
Telegram: https://t.me/+V7HSo1YNzkFkY2M1

**Comment by Pangu-Immortal** [comment]
Telegram: https://t.me/+V7HSo1YNzkFkY2M1
